DevForge_Connect/Entities/UserProfiles.cs
using DevForge_Connect.Entities.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DevForge_Connect.Entities
{
    public class UserProfile
    {
        public int Id { get; set; }

        [Required] public string? UserId { get; set; }
        public string? Bio { get; set; }
        public string? Expirience { get; set; }
        public byte[]? ProfilePicture { get; set; }
        public string? NlpTags { get; set; } = string.Empty;

        //Navigation Properties
        public ApplicationUser? User { get; set; } = null!;
    }
}

DevForge_Connect/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DevForge_Connect.Data;
using DevForge_Connect.Entities;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using DevForge_Connect.Entities.Identity;
using DevForge_Connect.Services.NLP_Translator;
using System.Text.Json;

namespace DevForge_Connect.Controllers
{
    [Authorize]
    public class UserProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ITranslator _nlTranslator;

        public UserProfilesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, ITranslator nlTranslator)
        {
            _context = context;
            _userManager = userManager;
            _nlTranslator = nlTranslator;
        }

        // GET: UserProfiles
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return NotFound();
            }

            var userProfile = await _context.UserProfile.Include(u => u.User).FirstOrDefaultAsync(u => u.UserId == userId);

            if (userProfile == null)
            {
                var default_PFP_Path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "default-pfp.jpeg");
                byte[] defaultPFP = System.IO.File.ReadAllBytes(default_PFP_Path);

                userProfile = new UserProfile
                {
                    UserId = userId,
                    Bio = "",
					Expirience = "",
                    ProfilePicture = defaultPFP
                };

                _context.UserProfile.Add(userProfile);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(userProfile);
        }

        // GET: UserProfiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfile = await _context.UserProfile
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProfile == null)
            {
                return NotFound();
            }

            return View(userProfile);
        }

        // GET: UserProfiles/Create
        public IActionResult Create()
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var userProfile = new UserProfile
            {
                UserId = currentUserId
            };

            return View(userProfile);
        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Bio,Expirience,ProfilePicture")] UserProfile userProfile, IFormFile profilePicture)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var userId = _userManager.GetUserId(User);
            if (currentUser != null)
                userProfile.UserId = currentUser.Id;


            if (profilePicture != null && profilePicture.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await profilePicture.CopyToAsync(memoryStream);
                    userProfile.ProfilePicture = memoryStream.ToArray();
                }
            }
            else
            {
                ModelState.Remove("ProfilePicture");
            }

            if (ModelState.IsValid)
            {
                _context.Add(userProfile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(userProfile);
        }

        // GET: UserProfiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfile = await _context.UserProfile.FindAsync(id);
            if (userProfile == null || userProfile.UserId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound();
            }

            return View(userProfile);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, UserProfile updatedProfile, IFormFile profilePicture)
        {
            if (id != updatedProfile.Id)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return Unauthorized();
            }

            var userProfile = await _context.UserProfile.FirstOrDefaultAsync(u => u.Id == id && u.UserId == currentUser.Id);

            if (userProfile == null)
            {
                return Unauthorized();
            }

            userProfile.Bio = updatedProfile.Bio;
            userProfile.Expirience = updatedProfile.Expirience;

            if (profilePicture != null && profilePicture.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await profilePicture.CopyToAsync(memoryStream);
                    userProfile.ProfilePicture = memoryStream.ToArray();
                }
            }
            else
            {
                ModelState.Remove("ProfilePicture");
            }



            if (ModelState.IsValid)
            {
                try
                {
                    string userNlpTags = await _nlTranslator.GetNlpTags([userProfile.Expirience]);
					var outerArray = JsonSerializer.Deserialize<string[][]>(userNlpTags);
                    var innerArray = outerArray[0];
                    string tag = "";
                    foreach (var item in innerArray)
                    {
                        tag = tag + "|" + item;
                    }
                    userProfile.NlpTags = tag;
					_context.Update(userProfile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserProfileExists(userProfile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userProfile = await _context.UserProfile
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userProfile == null)
            {
                return NotFound();
            }

            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userProfile = await _context.UserProfile.FindAsync(id);
            if (userProfile != null)
            {
                _context.UserProfile.Remove(userProfile);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserProfileExists(int id)
        {
            return _context.UserProfile.Any(e => e.Id == id);
        }

        public IActionResult GetProfilePicture(string userId)
        {
            var userProfile = _context.UserProfile.FirstOrDefault(u => u.UserId == userId);

            if (userProfile != null && userProfile.ProfilePicture != null)
            {
                return File(userProfile.ProfilePicture, "image/jpeg");
            }

            return File("~/images/default-pfp.jpeg", "image/jpeg");
        }
    }
}

DevForge_Connect/Views/UserProfiles/Create.cshtml
@model DevForge_Connect.Entities.UserProfile

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserProfile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Expirience" class="control-label"></label>
                <input asp-for="Expirience" class="form-control" />
                <span asp-validation-for="Expirience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label">Profile Picture</label>
                <input asp-for="ProfilePicture" class="form-control-file" type="file" accept=".jpeg,.jpg" />
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DevForge_Connect/Views/UserProfiles/Delete.cshtml
@model DevForge_Connect.Entities.UserProfile

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Expirience)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Expirience)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class="col-sm-10">
            @if (Model.ProfilePicture != null)
            {
                <img src="@Url.Action("GetProfilePicture", "UserProfiles", new { userId = Model.User.Id, t = DateTime.Now.Ticks })" alt="Profile Picture" style="width: 150px; height: 150px; border-radius: 50%;" />
            }
            else
            {
                <span>No Profile Picture Available</span>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DevForge_Connect/Views/UserProfiles/Details.cshtml
@model DevForge_Connect.Entities.UserProfile

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DevForge_Connect/Views/UserProfiles/Edit.cshtml
@model DevForge_Connect.Entities.UserProfile

@{
    ViewData["Title"] = "Edit Profile";
}

<h1 class="text-center">Edit Profile</h1>
<hr />
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card shadow-sm p-4 mb-5 bg-white rounded">
            <h4 class="card-title text-center">Update Your Profile</h4>
            <div class="card-body">
                <form asp-action="Edit" method="post" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                    <input type="hidden" asp-for="UserId" />
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label">Bio</label>
                        <textarea asp-for="Bio" class="form-control" placeholder="Write a short bio"></textarea>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Expirience" class="control-label">Expirience</label>
                        <textarea asp-for="Expirience" class="form-control" placeholder="Expirience"></textarea>
                        <span asp-validation-for="Expirience" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label">Profile Picture</label>
                        <input asp-for="ProfilePicture" class="form-control-file" type="file" accept=".jpeg,.jpg" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="ProfilePicture" />
                    <div class="form-group text-center">
                        <input type="submit" value="Save" class="btn btn-primary btn-block" />
                    </div>
                    <div class="form-group text-center">
                        <a asp-action="Index" class="btn btn-secondary btn-block">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DevForge_Connect/Views/UserProfiles/Index.cshtml
@using DevForge_Connect.Services.NLP_Translator
@using Microsoft.IdentityModel.Tokens
@model DevForge_Connect.Entities.UserProfile
@inject ITranslator _nlTranslator

@{
    ViewData["Title"] = "Profile";
}

<h1>Profile</h1>

<div class="profile-container text-center">
    <div class="profile-info">
        <img src="@(Model.ProfilePicture != null ? "data:image/png;base64," + Convert.ToBase64String(Model.ProfilePicture) : Url.Content("~/images/default-pfp.jpeg"))" alt="Profile Picture" width="150" height="150" class="profile-picture" />
        <div class="profile-details">
            <h3>@Model.User.FirstName @Model.User.LastName</h3>
            <p><strong>Bio:</strong> @Model.Bio</p>
            <p><strong>Experience:</strong> @Model.Expirience</p>
            <p><strong>Email:</strong> @Model.User.Email</p>
            @{
                if (Model.NlpTags != null && !Model.NlpTags.IsNullOrEmpty())
                {
                    <div class="fw-bold row">
                        <div class="row">
                            @{
                                // TODO - Make it so the badge color matches whether the current user has this skill
                                <div class="col"></div>
                                bool tagColor = false;
                                var tags = _nlTranslator.DecatNlpTags(Model.NlpTags);
                                int counter = 0;
                                foreach (var tag in tags)
                                {
                                    if (counter < 3)
                                    {
                                        if (tagColor)
                                        {
                                            <span class="badge badge-pill bg-danger col-3 m-1">@tag</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-pill bg-success col-3 m-1">@tag</span>
                                        }

                                        tagColor = !tagColor;
                                    }

                                    counter++;
                                }

                                <div class="col"></div>
                            }
                        </div>
                    </div>
                }
            }
        </div>
    </div>

    <a class="btn btn-primary w-100" asp-action="Edit" asp-route-id="@Model.Id">Edit Profile</a>
</div>