DevForge_Connect/Entities/ProjectSubmission.cs
using DevForge_Connect.Entities.Identity;
using Microsoft.Build.Framework;

namespace DevForge_Connect.Entities
{
    public class ProjectSubmission
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        public DateTime? Deadline { get; set; }
        public string Funding { get; set; } = string.Empty;

        [Required] public string? creatorId { get; set; }
        public ApplicationUser? Creator { get; set; }

        public int? StatusId { get; set; }
        public Status? Status { get; set; }

        public ICollection<ProjectBid> Bids { get; set; } = new List<ProjectBid>();
		public string? NlpTags { get; internal set; }

        public int? TeamId { get; set; }
        public Team? Team { get; set; }
	}
}

DevForge_Connect/Controllers/ProjectSubmissionsController.cs
using DevForge_Connect.Data;
using DevForge_Connect.Entities;
using DevForge_Connect.Entities.Identity;
using DevForge_Connect.Services.NLP_Translator;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Microsoft.Identity.Client;
using System.Net.WebSockets;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis;

namespace DevForge_Connect.Controllers
{
    public class ProjectSubmissionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ITranslator _translator;

        public ProjectSubmissionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, ITranslator translator)
        {
            _context = context;
            _userManager = userManager;
            _translator = translator;
        }


        // GET: ProjectSubmissions
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ProjectSubmissions.Include(p => p.Creator);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProjectSubmissions/Details/5
        public async Task<IActionResult> Details(int? id, List<int> requestsBid)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectSubmission = await _context.ProjectSubmissions
                .Include(p => p.Creator)
                .Include(p => p.Bids)
                .Include(p => p.Status)
                .FirstOrDefaultAsync(m => m.Id == id);

            foreach (var bid in projectSubmission.Bids)
            {
                if (bid.StatusId != null)
                {
                    bid.Status = await _context.Statuses.FindAsync(bid.StatusId);
                }
            }

            if (projectSubmission == null)
            {
                return NotFound();
            }

            return View(projectSubmission);
        }

        // GET: ProjectSubmissions/Create
        [Authorize]
        public IActionResult Create()
        {
            var userTeams = _context.UserTeams.Where(ut => ut.UserId.Equals(_userManager.GetUserId(User))).Include(ut => ut.Team);

            List<Team> teams = new List<Team>();

            foreach (var ut in userTeams)
            {
                if(ut.Team != null)
                    teams.Add(ut.Team);
            }

            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeamId"] = new SelectList(teams, "Id", "Name");

            var projectSubmission = new ProjectSubmission();
            projectSubmission.TeamId = -1;
            return View(projectSubmission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult ModifyProjectTitle([Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId,TeamId")] ProjectSubmission projectSubmission)
        {
            var userTeams = _context.UserTeams.Where(ut => ut.UserId.Equals(_userManager.GetUserId(User))).Include(ut => ut.Team);

            List<Team> teams = new List<Team>();

            foreach (var ut in userTeams)
            {
                if(ut.Team != null)
                    teams.Add(ut.Team);
            }

            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeamId"] = new SelectList(teams, "Id", "Name");

            return View(projectSubmission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult ModifyProjectDeadline([Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId,TeamId")] ProjectSubmission projectSubmission)
        {
            var userTeams = _context.UserTeams.Where(ut => ut.UserId.Equals(_userManager.GetUserId(User))).Include(ut => ut.Team);

            List<Team> teams = new List<Team>();

            foreach (var ut in userTeams)
            {
                if(ut.Team != null)
                    teams.Add(ut.Team);
            }

            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeamId"] = new SelectList(teams, "Id", "Name");

            return View(projectSubmission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult ModifyProjectDescription([Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId,TeamId")] ProjectSubmission projectSubmission)
        {
            var userTeams = _context.UserTeams.Where(ut => ut.UserId.Equals(_userManager.GetUserId(User))).Include(ut => ut.Team);

            List<Team> teams = new List<Team>();

            foreach (var ut in userTeams)
            {
                if(ut.Team != null)
                    teams.Add(ut.Team);
            }

            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeamId"] = new SelectList(teams, "Id", "Name");

            return View(projectSubmission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult ModifyProjectFunding([Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId,TeamId")] ProjectSubmission projectSubmission)
        {
            var userTeams = _context.UserTeams.Where(ut => ut.UserId.Equals(_userManager.GetUserId(User))).Include(ut => ut.Team);

            List<Team> teams = new List<Team>();

            foreach (var ut in userTeams)
            {
                if(ut.Team != null)
                    teams.Add(ut.Team);
            }

            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeamId"] = new SelectList(teams, "Id", "Name");

            return View(projectSubmission);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult ModifyProjectTeam([Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId,TeamId")] ProjectSubmission projectSubmission)
        {
            var userTeams = _context.UserTeams.Where(ut => ut.UserId.Equals(_userManager.GetUserId(User))).Include(ut => ut.Team);

            List<Team> teams = new List<Team>();

            foreach (var ut in userTeams)
            {
                if(ut.Team != null)
                    teams.Add(ut.Team);
            }

            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TeamId"] = new SelectList(teams, "Id", "Name");

            return View(projectSubmission);
        }

        // POST: ProjectSubmissions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId,TeamId")] ProjectSubmission projectSubmission)
        {
            //Assign the current user to project submission
            projectSubmission.creatorId = _userManager.GetUserId(User);

            //Convert project description into the string array
            string[] stringArrayDescription= Regex.Split(projectSubmission.Description, @"(?<=[.!?])\s+");

            //Get the NLP tags associated with project submission and assign to project

            string nlpTags = await _translator.GetNlpTags(stringArrayDescription);
            string top3NlpTags = _translator.GrabTop3Tags(nlpTags);

			projectSubmission.NlpTags = top3NlpTags;

            if (projectSubmission.TeamId == -1)
            {
                projectSubmission.TeamId = null;
            }

            if (ModelState.IsValid)
            {
                projectSubmission.StatusId = (await _context.Statuses.FirstOrDefaultAsync())!.Id;
                _context.Add(projectSubmission);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id", projectSubmission.creatorId);
            return View(projectSubmission);
        }

        // GET: ProjectSubmissions/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectSubmission = await _context.ProjectSubmissions.FindAsync(id);
            if (projectSubmission == null)
            {
                return NotFound();
            }
            ViewData["creatorId"] = new SelectList(_context.Users, "Id", "Id", projectSubmission.creatorId);
            return View(projectSubmission);
        }

        // POST: ProjectSubmissions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Deadline,Funding, AIGeneratedSummary, NlpTags, creatorId,StatusId")] ProjectSubmission projectSubmission)
        {
            if (id != projectSubmission.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

DevForge_Connect/Views/ProjectSubmissions/Create.cshtml
@model DevForge_Connect.Entities.ProjectSubmission

@{
    ViewData["Title"] = "Create";
}
<style>
    .container-fluid {
        padding: 2rem;
    }

    .navbar {
        height: 60px;
        padding: 0 1rem;
        margin: 0;
        background-color: #1e1e1e;
    }

    .navbar-brand, .nav-link {
        line-height: 60px;
        font-size: 1rem;
        color: #ffffff;
    }

    .navbar-collapse {
        margin: 0;
        padding: 0;
    }

    h2 {
        font-size: 2rem;
    }

    .chat-container {
        border: 2px solid #444;
        border-radius: 10px;
        background-color: #c6c6c6;
        color: #ffffff;
        padding: 1rem;
        display: flex;
        flex-direction: column;
        overflow-y: auto;
        scroll-snap-type: y mandatory;
    }

    .message {
        scroll-snap-align: end;
    }

    #experimentalChat {
        background-color: #121212;
        padding: 1rem;
        border-radius: 10px;
        color: #dcdcdc;
    }

    textarea, input {
        background-color: #282828;
        color: #ffffff;
        border: 1px solid #555;
        border-radius: 5px;
    }

    textarea:focus, input:focus {
        border-color: #007bff;
        outline: none;
    }

    .form-container input {
        width: 100%;
        margin-bottom: 10px;
    }

    .form-container button {
        width: 100%;
    }

    .chat-popup {
        display: none;
        position: fixed;
        bottom: 20px;
        right: 15px;
        width: 300px;
        background-color: #f8f9fa;
        border: 1px solid #ccc;
        border-radius: 10px;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.3);
        color: #333;
        z-index: 1000;
    }

    .form-container {
        padding: 15px;
        color: #333;
    }

    #messageInput {
        background-color: #fff;
        color: #333;
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 8px;
    }

    button, .btn {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 15px;
        font-weight: bold;
        border-radius: 5px;
        transition: background-color 0.3s;
    }

        button:hover, .btn:hover {
            background-color: #0056b3;
        }

    #sendButton, .btn-secondary {
        border-radius: 5px;
        padding: 10px 15px;
        font-weight: bold;
    }

        #sendButton:hover {
            background-color: #0056b3;
        }

        .btn-secondary:hover {
            background-color: #6c757d;
        }

    .open-button {
        position: fixed;
        bottom: 20px;
        right: 15px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 20px;
        padding: 12px 20px;
        font-size: 14px;
        cursor: pointer;
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);
        z-index: 1000;
    }

        .open-button:hover {
            background-color: #0056b3;
        }
</style>

<div class="container-fluid bg-light">
    <h2 class="text-center">Generate Project Information</h2>

    <hr />

    <form asp-action="ModifyProjectTitle" class="bg-light" id="projectform">
        <div class="row p-1 bg-light">

            <div class="col-3 bg-primary rounded-3 me-2 border border-black border-2 p-4 shadow">
                <p class="text-light border-bottom mb-5">- The chatbot can be used to flesh out project details and get more information about unknown tech stacks</p>
                <p class="text-light border-bottom">- Try to enter as much information as possible before moving on. This will save you time later on.</p>
            </div>
            @Html.HiddenFor(p => p.Title)
            @Html.HiddenFor(p => p.Description)
            @Html.HiddenFor(p => p.Deadline)
            @Html.HiddenFor(p => p.Funding)
            @Html.HiddenFor(p => p.TeamId)
            @Html.HiddenFor(p => p.creatorId)
            <div class="col-6 border border-black border-2 rounded-3 bg-dark shadow p-2">
                <div class="container-fluid">
                    <div class="row d-flex overflow-auto overflow-y-scroll" id="experimentalChat" style="height: 700px;">
                    </div>
                    <div class="row">
                        <div class="form-group col-9 p-0">
                            <textarea class="form-control bg-dark text-light" type="text" style="height: 20px;" id="ExperimentalInput"></textarea>
                            <span class="text-danger"></span>
                        </div>
                        <btn class="btn btn-dark col-3" id="ExperimentalSendChat">
                            Talk to Gemini
                        </btn>
                    </div>
                </div>                
            </div>
            <div class="col-2"></div>
        </div>
        <div class="form-group row p-3">
            <input type="submit" value="Submit Project Idea" id="SubmitAIProjectButton" class="col btn btn-outline-primary fw-bolder" />
        </div>
    </form>
    
    <hr />

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

<button id="openBtn" class="open-button" onclick="openForm()">Project Assistant</button>
<div class="chat-popup form-container" id="myForm">
    <h1>Chat Bot</h1>
    <div class="overflow-auto" style="max-height: 400px;">
        <div id="messages" style="overflow-anchor:none"></div>

        <hr />

        <div class="input-group mb-3">
            <input type="text" id="messageInput" class="form-control" placeholder="Send message" />

            <div class="input-group-append">
                <button type="submit" id="sendButton" class="btn btn-primary">Send</button>
                <button type="button" class="btn btn-secondary" onclick="closeForm()">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    function openForm() {
        document.getElementById("myForm").style.display = "block";
        document.getElementById("openBtn").style.display = "none";
    }

    function closeForm() {
        document.getElementById("myForm").style.display = "none";
        document.getElementById("openBtn").style.display = "block";
    }
</script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
    <script type="text/javascript" src="~/js/LLM_API/api.js"></script>
}

DevForge_Connect/Views/ProjectSubmissions/Index.cshtml
@using DevForge_Connect.Entities.Identity
@using DevForge_Connect.Services.NLP_Translator
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.IdentityModel.Tokens
@model IEnumerable<DevForge_Connect.Entities.ProjectSubmission>
@inject ITranslator _nlTranslator
@inject UserManager<ApplicationUser> _userManager;

@{
    ViewData["Title"] = "Index";
}

<h1>Projects</h1>

<div class="row">
    <a asp-action="Create" class="col btn-outline-success btn">Create New</a>
</div>

<div class="table-responsive" >
    <table class="table stripe" id="MyProjectTable" data-page-length="5">
        <thead>
        <tr>
            <th class="col-10">
                My Projects
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Funding)
            </th>
        </tr>
        </thead>
        <tbody>
        
        @foreach (var item in Model) {
                @if (_userManager.GetUserId(User).Equals(@item.creatorId)){
            <tr>
                <td class="col-6 m-auto text-center border-bottom" style="white-space: pre-line">
                    <div class="row border-bottom text-center">
                                <a class="fw-bold h5 link-primary" asp-controller="ProjectSubmissions" asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
                    </div>
                    @* @Html.DisplayFor(modelItem => item.Description) *@
                    
                            @{
                                string description = "No Description Found"; // Initialize with a default value

                                if (!string.IsNullOrEmpty(item.Description)) // Check if Description is NOT null or empty
                                {
                                    description = item.Description; // Assign item.Description to description
                                }

                                if (description.Length > 1000) // Truncate if the length exceeds 1000 characters
                                {
                                    description = description.Substring(0, 978) + "...";
                                }

                        
                     
                        <div class="row border-bottom">
                            <div class="row text-start">
                                <div class="col-1"></div>
                                <div class="col">@description</div>
                                <div class="col-1"></div>
                            </div>
                            @if (item.Description.Length > 1000)
                            {
                                <div class="text-end row">
                                    <a class="btn btn-link text-end" asp-controller="ProjectSubmissions" asp-action="Details" asp-route-id="@item.Id">View More Details</a>
                                </div>
                            }
                                <div class="text-end row fw-bold">
                                    <div class="col"></div>
                                    <div class="col-6 row">
                                        <div class="col">Created By:</div>
                                        <p class="text-end col fw-bold text-black">@item.Creator.Email</p>
                                    </div>
                                </div>
                                <hr>
                                    @{
                                        if (item.NlpTags != null && !item.NlpTags.IsNullOrEmpty())
                                        {
                                            <div class="h5 fw-bold row">
                                                <div class="row">
                                                    <div class="col">NLP Tags</div>
                                                </div>
                                                <div class="row">
                                                    @{
                                                        // TODO - Make it so the badge color matches whether the current user has this skill
                                                        <div class="col"></div>
                                                        bool tagColor = false;
                                                        var tags = _nlTranslator.DecatNlpTags(item.NlpTags);
                                                        foreach (var tag in tags)
                                                        {
                                                            if (tagColor)
                                                            {
                                                                <span class="badge badge-pill bg-danger col-2 m-1">@tag</span>
                                                            }
                                                            else
                                                            {
                                                                <span class="badge badge-pill bg-success col-2 m-1">@tag</span>
                                                            }

                                                            tagColor = !tagColor;
                                                        }

                                                        <div class="col"></div>
                                                    }
                                                </div>
                                            </div>
                                        }
                                    }
                            
                            <div class="row">
                               
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary col">Edit</a>
                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger col">Delete</a>
                                
                            </div>
                        </div>
                    }

            
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Deadline)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Funding)
                </td>
            </tr>
        }
        }
        </tbody>
    </table>
</div>

<div class="table-responsive">
    <table class="table stripe" id="ProjectTable" data-page-length="25">
        <thead>
            <tr>
                <th class="col-10">
                    All Projects
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Deadline)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Funding)
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                @if (!(_userManager.GetUserId(User).Equals(@item.creatorId)))
                {
                    <tr>
                        <td class="col-6 m-auto text-center border-bottom" style="white-space: pre-line">
                            <div class="row border-bottom text-center">
                                <a class="fw-bold h5 link-primary" asp-controller="ProjectSubmissions" asp-action="Details" asp-route-id="@item.Id">@item.Title</a>
                            </div>
                            @* @Html.DisplayFor(modelItem => item.Description) *@

                            @{
                                
                                string description = "No Description Found"; // Initialize with a default value

                                if (!string.IsNullOrEmpty(item.Description)) // Check if Description is NOT null or empty
                                {
                                    description = item.Description; // Assign item.Description to description
                                }

                                if (description.Length > 1000) // Truncate if the length exceeds 1000 characters
                                {
                                    description = description.Substring(0, 978) + "...";
                                }

                                <div class="row border-bottom">
                                    <div class="row text-start">
                                        <div class="col-1"></div>
                                        <div class="col">@description</div>
                                        <div class="col-1"></div>
                                    </div>
                                    @if (item.Description.Length > 1000)
                                    {
                                        <div class="text-end row">
                                            <a class="btn btn-link text-end" asp-controller="ProjectSubmissions" asp-action="Details" asp-route-id="@item.Id">View More Details</a>
                                        </div>
                                    }
                                    <div class="text-end row fw-bold">
                                            <div class="col"></div>
                                            <div class="col-6 row">
                                                <div class="col">Created By:</div>
                                                <p class="text-end col fw-bold text-black">@item.Creator.Email</p>
                                            </div>
                                        </div>
                                    <hr>
                                    @{
                                        if (item.NlpTags != null && !item.NlpTags.IsNullOrEmpty())
                                        {
                                            <div class="h5 fw-bold row">
                                                <div class="row">
                                                    <div class="col">NLP Tags</div>
                                                </div>
                                                <div class="row">
                                                    @{
                                                        // TODO - Make it so the badge color matches whether the current user has this skill
                                                        <div class="col"></div>
                                                        bool tagColor = false;
                                                        var tags = _nlTranslator.DecatNlpTags(item.NlpTags);
                                                        foreach (var tag in tags)
                                                        {
                                                            if (tagColor)
                                                            {
                                                                <span class="badge badge-pill bg-danger col-2 m-1">@tag</span>
                                                            }
                                                            else
                                                            {
                                                                <span class="badge badge-pill bg-success col-2 m-1">@tag</span>
                                                            }

                                                            tagColor = !tagColor;
                                                        }

                                                        <div class="col"></div>
                                                    }
                                                </div>
                                            </div>
                                        }
                                    }
                                    <div class="row">
                                        @if (User.IsInRole("admin"))
                                        {
                                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary col">Edit</a>
                                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger col">Delete</a>
                                        }
                                    </div>
                                </div>
                            }

                            
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Deadline)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Funding)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@section Scripts
{
    <script type="text/javascript" src="~/js/Table_Initializers/ProjectSubmissionTable.js"></script>
}